/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ContextUpgradeableContract } from "./ContextUpgradeable";
import { InitializableContract } from "./Initializable";
import { JobCenterContract } from "./JobCenter";
import { MigrationsContract } from "./Migrations";
import { OwnableUpgradeableContract } from "./OwnableUpgradeable";
import { ServiceRegistryContract } from "./ServiceRegistry";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "ContextUpgradeable"): ContextUpgradeableContract;
      require(name: "Initializable"): InitializableContract;
      require(name: "JobCenter"): JobCenterContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "OwnableUpgradeable"): OwnableUpgradeableContract;
      require(name: "ServiceRegistry"): ServiceRegistryContract;
    }
  }
}

export {
  ContextUpgradeableContract,
  ContextUpgradeableInstance,
} from "./ContextUpgradeable";
export { InitializableContract, InitializableInstance } from "./Initializable";
export { JobCenterContract, JobCenterInstance } from "./JobCenter";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export {
  OwnableUpgradeableContract,
  OwnableUpgradeableInstance,
} from "./OwnableUpgradeable";
export {
  ServiceRegistryContract,
  ServiceRegistryInstance,
} from "./ServiceRegistry";
