# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import transcoding_pb2 as transcoding__pb2


class TranscoderStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DispatchVoDTask = channel.unary_stream(
                '/transcode.Transcoder/DispatchVoDTask',
                request_serializer=transcoding__pb2.DispatchVoDRequest.SerializeToString,
                response_deserializer=transcoding__pb2.TaskResult.FromString,
                )


class TranscoderServicer(object):
    """The greeting service definition.
    """

    def DispatchVoDTask(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranscoderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DispatchVoDTask': grpc.unary_stream_rpc_method_handler(
                    servicer.DispatchVoDTask,
                    request_deserializer=transcoding__pb2.DispatchVoDRequest.FromString,
                    response_serializer=transcoding__pb2.TaskResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transcode.Transcoder', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Transcoder(object):
    """The greeting service definition.
    """

    @staticmethod
    def DispatchVoDTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/transcode.Transcoder/DispatchVoDTask',
            transcoding__pb2.DispatchVoDRequest.SerializeToString,
            transcoding__pb2.TaskResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
