# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transcoding.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

from google.protobuf.timestamp_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11transcoding.proto\x12\ttranscode\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x01\n\tVideoInfo\x12\x0b\n\x03vid\x18\x01 \x01(\t\x12\x10\n\x08\x64uration\x18\x02 \x01(\t\x12*\n\x0borigincodec\x18\x03 \x01(\x0e\x32\x15.transcode.VideoCodec\x12/\n\x10originresolution\x18\x04 \x01(\x0e\x32\x15.transcode.Resolution\x12/\n\x10originaudiocodec\x18\x05 \x01(\x0e\x32\x15.transcode.AudioCodec\x12\x17\n\x0foriginframerate\x18\x06 \x01(\t\x12\x15\n\roriginbitrate\x18\x07 \x01(\t\"u\n\x12\x44ispatchVoDRequest\x12\x0e\n\x06taskid\x18\x01 \x01(\t\x12\x11\n\toriginurl\x18\x02 \x01(\t\x12*\n\x0boutputcodec\x18\x03 \x01(\x0e\x32\x15.transcode.VideoCodec\x12\x10\n\x08uniqueid\x18\x04 \x01(\t\"C\n\nTaskResult\x12%\n\x06status\x18\x01 \x01(\x0e\x32\x15.transcode.TaskStatus\x12\x0e\n\x06taskid\x18\x02 \x01(\t*B\n\nTaskStatus\x12\x0b\n\x07\x45NQUEUE\x10\x00\x12\x0c\n\x08\x45XECUTED\x10\x01\x12\r\n\tEVALUATED\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03*2\n\nVideoCodec\x12\x08\n\x04H264\x10\x00\x12\x08\n\x04H265\x10\x01\x12\x07\n\x03VP9\x10\x02\x12\x07\n\x03\x41V1\x10\x03*\x1f\n\nAudioCodec\x12\x07\n\x03\x41\x41\x43\x10\x00\x12\x08\n\x04NONE\x10\x01*%\n\nResolution\x12\x06\n\x02SD\x10\x00\x12\x06\n\x02HD\x10\x01\x12\x07\n\x03\x46HD\x10\x02*3\n\x07\x42itrate\x12\x07\n\x03LOW\x10\x00\x12\n\n\x06MEDIUM\x10\x01\x12\x08\n\x04HIGH\x10\x02\x12\t\n\x05ULTRA\x10\x03**\n\x08TaskType\x12\x07\n\x03VOD\x10\x00\x12\x0b\n\x07LATENCY\x10\x01\x12\x08\n\x04LIVE\x10\x02\x32Y\n\nTranscoder\x12K\n\x0f\x44ispatchVoDTask\x12\x1d.transcode.DispatchVoDRequest\x1a\x15.transcode.TaskResult\"\x00\x30\x01P\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcoding_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TASKSTATUS._serialized_start=488
  _TASKSTATUS._serialized_end=554
  _VIDEOCODEC._serialized_start=556
  _VIDEOCODEC._serialized_end=606
  _AUDIOCODEC._serialized_start=608
  _AUDIOCODEC._serialized_end=639
  _RESOLUTION._serialized_start=641
  _RESOLUTION._serialized_end=678
  _BITRATE._serialized_start=680
  _BITRATE._serialized_end=731
  _TASKTYPE._serialized_start=733
  _TASKTYPE._serialized_end=775
  _VIDEOINFO._serialized_start=66
  _VIDEOINFO._serialized_end=298
  _DISPATCHVODREQUEST._serialized_start=300
  _DISPATCHVODREQUEST._serialized_end=417
  _TASKRESULT._serialized_start=419
  _TASKRESULT._serialized_end=486
  _TRANSCODER._serialized_start=777
  _TRANSCODER._serialized_end=866
# @@protoc_insertion_point(module_scope)
